import Foundation

enum BackupLocalization {
    static let english: [String: String] = [
        "备份与恢复": "Backup and Restore",
        "用独立密码加密聊天、任务、已保存设置和容器配置，可选包含钥匙串凭据与日志。请先保存设置。": "Encrypt chats, tasks, saved settings and container configuration with a separate password. Credentials and logs are optional. Save your settings first.",
        "创建加密备份…": "Create Encrypted Backup…",
        "从备份恢复…": "Restore from Backup…",
        "选择加密备份": "Select Encrypted Backup",
        "备份密码丢失后无法恢复。备份不包含开发目录、.env、更新签名私钥或缓存。": "A lost backup password cannot be recovered. Development directories, .env, update signing keys and caches are excluded.",
        "显示恢复前备份": "Show Pre-Restore Backup",
        "备份密码": "Backup Password",
        "至少 12 个字符": "At least 12 characters",
        "再次输入备份密码": "Confirm Backup Password",
        "包含钥匙串密码和 API Key": "Include Keychain passwords and API keys",
        "包含后端日志": "Include backend logs",
        "密码不会保存在备份文件中。请将备份密码保存在安全的位置。": "The password is not stored in the backup. Keep it in a safe place.",
        "备份时间：{0}": "Backup created: {0}",
        "来源版本：{0}；会话：{1}；任务：{2}": "Source version: {0}; conversations: {1}; tasks: {2}",
        "恢复聊天与任务（替换当前记录）": "Restore chats and tasks (replace current records)",
        "恢复已保存设置和容器配置": "Restore saved settings and container configuration",
        "恢复钥匙串凭据（覆盖同名条目）": "Restore Keychain credentials (overwrite matching entries)",
        "恢复后端日志": "Restore backend logs",
        "恢复会暂停后端并要求重新登录。恢复前自动生成加密备份，使用本次输入的同一密码。": "Restore stops the backend and requires signing in again. An encrypted pre-restore backup is created using the same password you entered.",
        "正在处理备份…": "Processing backup…",
        "保存加密备份…": "Save Encrypted Backup…",
        "验证并预览": "Verify and Preview",
        "恢复所选数据…": "Restore Selected Data…",
        "确认恢复所选数据？": "Restore selected data?",
        "恢复": "Restore",
        "选中的数据将覆盖当前数据，正在执行的请求会中断。恢复前备份可用于撤销本次恢复。": "Selected data will overwrite current data and interrupt active requests. The pre-restore backup can undo this restore.",
        "备份密码至少需要 12 个字符，且不超过 1024 字节。": "Use a backup password of at least 12 characters and no more than 1024 UTF-8 bytes.",
        "备份格式不支持，或数据校验失败。": "The backup format is unsupported or its data failed validation.",
        "密码不正确，或备份文件已损坏。": "The password is incorrect or the backup is damaged.",
        "备份超过 128 MB 限制，请减少日志或清理历史后重试。": "The backup exceeds 128 MB. Exclude logs or reduce history and try again.",
        "无法安全读取或恢复聊天数据库，请检查文件权限和数据库状态。": "Cannot safely read or restore the chat database. Check permissions and database status.",
        "无法读取或写入全部钥匙串凭据，操作已停止。": "Cannot read or write all Keychain credentials. The operation was stopped.",
        "备份与恢复仅支持本机后端，请先切换到本机地址。": "Backup and restore require a local backend. Switch to a local address first.",
        "请先停止外部启动的后端，再进行恢复。": "Stop the externally started backend before restoring.",
        "后端尚未完全停止，未执行恢复。": "The backend has not fully stopped. No restore was performed.",
        "恢复及回滚未能全部完成。请保留并使用恢复前备份：{0}": "Restore and rollback did not fully complete. Keep and use the pre-restore backup: {0}",
        "加密备份已保存：{0}": "Encrypted backup saved: {0}",
        "备份已恢复，请重新登录。": "Backup restored. Please sign in again.",
    ]

    static let norwegian: [String: String] = [
        "备份与恢复": "Sikkerhetskopiering og gjenoppretting",
        "用独立密码加密聊天、任务、已保存设置和容器配置，可选包含钥匙串凭据与日志。请先保存设置。": "Krypter samtaler, oppgaver, lagrede innstillinger og containeroppsett med et eget passord. Nøkkelringdata og logger er valgfrie. Lagre innstillingene først.",
        "创建加密备份…": "Opprett kryptert sikkerhetskopi…",
        "从备份恢复…": "Gjenopprett fra sikkerhetskopi…",
        "选择加密备份": "Velg kryptert sikkerhetskopi",
        "备份密码丢失后无法恢复。备份不包含开发目录、.env、更新签名私钥或缓存。": "Et mistet passord kan ikke gjenopprettes. Utviklingsmapper, .env, private oppdateringsnøkler og hurtigbuffer er utelatt.",
        "显示恢复前备份": "Vis kopi fra før gjenoppretting",
        "备份密码": "Passord for sikkerhetskopi",
        "至少 12 个字符": "Minst 12 tegn",
        "再次输入备份密码": "Bekreft passordet",
        "包含钥匙串密码和 API Key": "Ta med nøkkelringpassord og API-nøkler",
        "包含后端日志": "Ta med backendlogger",
        "密码不会保存在备份文件中。请将备份密码保存在安全的位置。": "Passordet lagres ikke i sikkerhetskopien. Oppbevar det trygt.",
        "备份时间：{0}": "Opprettet: {0}",
        "来源版本：{0}；会话：{1}；任务：{2}": "Kildeversjon: {0}; samtaler: {1}; oppgaver: {2}",
        "恢复聊天与任务（替换当前记录）": "Gjenopprett samtaler og oppgaver (erstatt eksisterende)",
        "恢复已保存设置和容器配置": "Gjenopprett lagrede innstillinger og containeroppsett",
        "恢复钥匙串凭据（覆盖同名条目）": "Gjenopprett nøkkelringdata (overskriv like navn)",
        "恢复后端日志": "Gjenopprett backendlogger",
        "恢复会暂停后端并要求重新登录。恢复前自动生成加密备份，使用本次输入的同一密码。": "Gjenoppretting stopper backenden og krever ny innlogging. En kryptert kopi opprettes først med passordet du oppga.",
        "正在处理备份…": "Behandler sikkerhetskopi…",
        "保存加密备份…": "Lagre kryptert sikkerhetskopi…",
        "验证并预览": "Kontroller og forhåndsvis",
        "恢复所选数据…": "Gjenopprett valgte data…",
        "确认恢复所选数据？": "Gjenopprette valgte data?",
        "恢复": "Gjenopprett",
        "选中的数据将覆盖当前数据，正在执行的请求会中断。恢复前备份可用于撤销本次恢复。": "Valgte data erstatter eksisterende data og avbryter aktive forespørsler. Kopien fra før gjenoppretting kan brukes til å angre.",
        "备份密码至少需要 12 个字符，且不超过 1024 字节。": "Passordet må ha minst 12 tegn og maksimalt 1024 UTF-8-byte.",
        "备份格式不支持，或数据校验失败。": "Formatet støttes ikke, eller kontrollen av dataene mislyktes.",
        "密码不正确，或备份文件已损坏。": "Passordet er feil, eller sikkerhetskopien er skadet.",
        "备份超过 128 MB 限制，请减少日志或清理历史后重试。": "Sikkerhetskopien overstiger 128 MB. Utelat logger eller reduser historikken og prøv igjen.",
        "无法安全读取或恢复聊天数据库，请检查文件权限和数据库状态。": "Kan ikke lese eller gjenopprette databasen trygt. Kontroller tilganger og databasestatus.",
        "无法读取或写入全部钥匙串凭据，操作已停止。": "Kan ikke lese eller skrive alle nøkkelringdata. Operasjonen ble stoppet.",
        "备份与恢复仅支持本机后端，请先切换到本机地址。": "Sikkerhetskopiering og gjenoppretting krever en lokal backend. Bytt til en lokal adresse først.",
        "请先停止外部启动的后端，再进行恢复。": "Stopp den eksternt startede backenden før gjenoppretting.",
        "后端尚未完全停止，未执行恢复。": "Backenden har ikke stoppet helt. Ingen gjenoppretting ble utført.",
        "恢复及回滚未能全部完成。请保留并使用恢复前备份：{0}": "Gjenoppretting og tilbakerulling ble ikke fullført. Behold og bruk kopien fra før gjenoppretting: {0}",
        "加密备份已保存：{0}": "Kryptert sikkerhetskopi lagret: {0}",
        "备份已恢复，请重新登录。": "Sikkerhetskopien er gjenopprettet. Logg inn på nytt.",
    ]
}
