import Foundation

/// 英文译文表（English）
/// key = 源码里写的中文原文（`{0}` / `{1}` 是占位符，见 Localizer.t）
enum LocalizationTableEN {
    static let table: [String: String] = [
        "AI Provider（密钥存 Keychain，启动时传给 Python）": "AI Provider (keys live in the Keychain and are passed to Python on launch)",
        "AI 正在执行工具调用，可能需要 1-2 分钟": "The AI is running tool calls; this can take 1–2 minutes",
        "Azure Foundry 填 https://<资源名>.openai.azure.com/openai/v1": "For Azure Foundry enter https://<resource-name>.openai.azure.com/openai/v1",
        "Azure Portal → Microsoft Entra ID → 概述 → 租户 ID": "Azure Portal → Microsoft Entra ID → Overview → Tenant ID",
        "Azure Portal → 应用注册 → 你的应用 → 应用程序(客户端) ID": "Azure Portal → App registrations → your app → Application (client) ID",
        "Azure Portal → 订阅 → 订阅 ID": "Azure Portal → Subscriptions → Subscription ID",
        "Azure 上填部署名（例如 gpt-5.6-sol）；OpenAI 上填模型名": "On Azure enter the deployment name (e.g. gpt-5.6-sol); on OpenAI enter the model name",
        "Azure 凭据": "Azure credentials",
        "Azure 工具凭据": "Azure tool credentials",
        "Azure 工具（enable_tools=true 时使用）": "Azure tools (used when enable_tools=true)",
        "Azure：{0}": "Azure: {0}",
        "Bundle 里没有内嵌后端，也没在 {0} 里找到 main.py": "No bundled backend in the app, and no main.py in {0}",
        "Client ID 来自 Google Cloud 的桌面应用 OAuth Client。邮箱和域名用逗号分隔；两者都留空会允许所有 Google 账号。": "The Client ID comes from a Google Cloud desktop OAuth client. Separate emails and domains with commas; leaving both empty allows any Google account.",
        "GitHub 登录失败": "GitHub sign-in failed",
        "GitHub 登录已超时，请重试": "GitHub sign-in timed out, please try again",
        "GitHub 登录成功，但后端没有返回 JWT": "GitHub sign-in succeeded, but the backend returned no JWT",
        "GitHub 验证码 {0} 已复制，请在浏览器中粘贴": "GitHub device code {0} copied — paste it into the browser",
        "Google 登录失败": "Google sign-in failed",
        "Google 登录已超时，请重试": "Google sign-in timed out, please try again",
        "Google 登录成功，但后端没有返回 JWT": "Google sign-in succeeded, but the backend returned no JWT",
        "Keychain 中的数据无法解析": "The data in the Keychain cannot be read",
        "Keychain 操作失败，状态码 {0}": "Keychain operation failed, status {0}",
        "Keychain 操作失败：{0}（{1}）": "Keychain operation failed: {0} ({1})",
        "Meraki 凭据": "Meraki credentials",
        "Meraki 工具凭据": "Meraki tool credentials",
        "Meraki 工具（enable_tools=true 时使用）": "Meraki tools (used when enable_tools=true)",
        "Meraki：{0}": "Meraki: {0}",
        "Moonshot / Kimi 开放平台 → API Keys": "Moonshot / Kimi platform → API Keys",
        "Nexus Dashboard 凭据": "Nexus Dashboard credentials",
        "Nexus Dashboard 工具凭据": "Nexus Dashboard tool credentials",
        "Nexus Dashboard 工具（官方 Infra API + Manage API）": "Nexus Dashboard tools (official Infra API + Manage API)",
        "Nexus Dashboard 的本地账号（API Key 只对 local 账号有效）": "A local Nexus Dashboard account (API keys only work for local accounts)",
        "Nexus Dashboard 集群地址：只填主机名/IP，不要带 /api/v1/...（后端自动拼 Infra 与 Manage 两套基地址）": "Nexus Dashboard address: host name or IP only, without /api/v1/... (the backend builds both the Infra and Manage base URLs)",
        "OpenAI: platform.openai.com → API keys；Azure Foundry 用 Azure 门户里的 Key": "OpenAI: platform.openai.com → API keys; for Azure Foundry use the key from the Azure portal",
        "Python 环境": "Python environment",
        "Python 解释器": "Python interpreter",
        "Python 解释器不可执行：{0}": "The Python interpreter is not executable: {0}",
        "memory：重启会丢历史": "memory: history is lost on restart",
        "mock 模式（后端未配置 API Key）": "mock mode (no API key configured in the backend)",
        "sk-…（留空则 DeepSeek 走 mock 回复）": "sk-… (leave empty and DeepSeek answers with mocks)",
        "sk-…（留空则 Kimi 走 mock 回复）": "sk-… (leave empty and Kimi answers with mocks)",
        "sk-…（留空则 OpenAI 走 mock 回复）": "sk-… (leave empty and OpenAI answers with mocks)",
        "sqlite（重启保留历史）": "sqlite (history survives restarts)",
        "{0} 条消息": "{0} messages",
        "{0}：重启可能丢历史": "{0}: history may be lost on restart",
        "{0}｜原始响应：{1}": "{0}｜Raw response: {1}",
        "⚠ 有失败": "⚠ failures",
        "✓ 可以登录了（存储为 memory，重启会丢历史）": "✓ You can sign in (storage is memory, history is lost on restart)",
        "✓ 配置完整，可以登录了": "✓ Everything is configured, you can sign in",
        "一键重启并测试": "Restart and test",
        "仅在不用 API Key 时填写": "Fill in only if you are not using an API key",
        "任务已受理（{0}…），等待结果…": "Task accepted ({0}…), waiting for the result…",
        "任务执行失败": "The task failed",
        "会话": "Conversations",
        "使用 GitHub 账号登录": "Sign in with GitHub",
        "使用 Google 账号登录": "Sign in with Google",
        "依赖检查通过（原生 arm64）：{0}": "Dependency check passed (native arm64): {0}",
        "保存 Azure 凭据": "Save Azure credentials",
        "保存 Meraki 凭据": "Save Meraki credentials",
        "保存 Nexus Dashboard 凭据": "Save Nexus Dashboard credentials",
        "保存凭据失败：{0}": "Failed to save credentials: {0}",
        "保存到 Keychain": "Save to Keychain",
        "保存失败：{0}": "Save failed: {0}",
        "保存并重启后端": "Save and restart the backend",
        "保存设置": "Save settings",
        "停止": "Stop",
        "允许的域名": "Allowed domains",
        "允许的用户名": "Allowed user names",
        "允许的邮箱": "Allowed emails",
        "关闭": "Close",
        "内嵌后端已就绪": "Bundled backend is ready",
        "写入 .env": "Write .env",
        "写入失败：{0}": "Write failed: {0}",
        "凭据已更新，需要重启后端生效": "Credentials updated; restart the backend to apply them",
        "切换语言后立即生效，不用重启应用。": "Takes effect immediately — no need to restart the app.",
        "删除这个会话": "Delete this conversation",
        "刷新状态": "Refresh status",
        "去配置": "Configure",
        "发送": "Send",
        "取消": "Cancel",
        "只有在没有内嵌后端、需要跑项目里的 main.py 时才会用到这两项。": "These two are only needed when there is no bundled backend and main.py from the project directory has to be used.",
        "只读工具：Infra API 覆盖集群/节点/健康/容量/许可/租户/集成，Manage API 覆盖 fabric/交换机/接口/网络/VRF，不含任何写操作。": "Read-only tools: the Infra API covers clusters/nodes/health/capacity/licensing/tenants/integrations; the Manage API covers fabric/switches/interfaces/networks/VRFs. No write operations.",
        "右上角用户名 → Manage API keys → Add API key。留空则后端用 ND_PASSWORD 调 /api/v1/infra/login 换 token": "User name in the top right → Manage API keys → Add API key. If left empty, the backend uses ND_PASSWORD against /api/v1/infra/login to get a token",
        "后端 {0} 秒内没有响应，请检查依赖与日志": "The backend did not respond within {0} seconds; check dependencies and the logs",
        "后端地址": "Backend address",
        "后端地址无效：{0}": "Invalid backend address: {0}",
        "后端日志": "Backend logs",
        "后端未上报存储类型": "The backend did not report a storage type",
        "后端未启用工具，请检查设置": "Tools are not enabled in the backend — check the settings",
        "后端未运行": "Backend not running",
        "后端未运行，需要先启动后端": "The backend is not running; start it first",
        "后端模式：内嵌 backend_server（下次启动生效）｜日志：{0}": "Backend mode: bundled backend_server (applies after the next launch)｜Log: {0}",
        "后端模式：内嵌 backend_server｜日志：{0}": "Backend mode: bundled backend_server｜Log: {0}",
        "后端模式：开发模式（没找到内嵌 backend_server，回退到项目目录 + Python）": "Backend mode: development mode (no bundled backend_server found, falling back to the project directory + Python)",
        "后端没起来：{0}": "The backend did not come up: {0}",
        "后端状态异常：{0}": "Unexpected backend status: {0}",
        "后端进程": "Backend process",
        "后端重启失败：{0}": "Restarting the backend failed: {0}",
        "启动": "Start",
        "启动中…": "Starting…",
        "启动后端": "Start backend",
        "启动失败：{0}": "Start failed: {0}",
        "启动应用时自动拉起本地后端": "Start the local backend automatically when the app launches",
        "启动时把设置写入项目根目录的 .env": "On launch, write the settings into .env in the project root",
        "响应为空": "Empty response",
        "响应类型异常": "Unexpected response type",
        "字体大小 {0}%": "Font size {0}%",
        "存储": "Storage",
        "存储后端：": "Storage backend:",
        "客户端密码的 Value": "Client secret Value",
        "密码": "Password",
        "密码模式的登录域，本地账号填 local；对接外部认证域时填对应域名": "Login domain for password mode; use local for local accounts, or the matching domain for external authentication",
        "密码模式：后端 POST /api/v1/infra/login 拿 jwttoken，进程内缓存 10 分钟后自动续期": "Password mode: the backend POSTs to /api/v1/infra/login for a JWT, caches it for 10 minutes and renews it automatically",
        "对话": "Chat",
        "工具": "Tools",
        "工具凭据：": "Tool credentials:",
        "工具调用已关闭，纯对话模式": "Tool calls are off — plain chat",
        "工具调用已开启，AI 可执行 Azure/Meraki 查询": "Tool calls are on — the AI can run Azure/Meraki queries",
        "已使用 GitHub 账号登录": "Signed in with GitHub",
        "已使用 Google 账号登录": "Signed in with Google",
        "已写入：{0}": "Written to: {0}",
        "已取消本次请求": "Request cancelled",
        "已启用工具调用": "Tool calls enabled",
        "已启用工具调用：AI 可能会查询你的 Azure 订阅或 Meraki 网络。每次调用都会在气泡中显示。": "Tool calls are enabled: the AI may query your Azure subscriptions or Meraki networks. Every call is shown in the message bubble.",
        "已就绪（后端未上报版本）": "Ready (the backend did not report a version)",
        "已检测到 Azure 凭据": "Azure credentials detected",
        "已检测到 Meraki 凭据": "Meraki credentials detected",
        "已检测到 Nexus Dashboard 凭据": "Nexus Dashboard credentials detected",
        "已连接 {0}": "Connected to {0}",
        "已退出登录": "Signed out",
        "已配置": "Configured",
        "已配置 {0}": "Configured: {0}",
        "已配置（az login 凭据）": "Configured (az login credentials)",
        "已配置（环境变量）": "Configured (environment variables)",
        "应用注册 → 证书和密码 → 新客户端密码（复制 Value，不是 Secret ID）": "App registrations → Certificates & secrets → New client secret (copy the Value, not the Secret ID)",
        "应用（客户端）ID": "Application (client) ID",
        "开始新的对话": "Start a new conversation",
        "当前后端进程：{0}。凭据改动需要重启后端才会生效。": "Current backend process: {0}. Credential changes take effect after the backend is restarted.",
        "恢复默认字体大小": "Reset font size to default",
        "我": "Me",
        "或使用本地管理员（应急入口）": "Or use the local administrator (emergency access)",
        "打开后端日志": "Open the backend log",
        "放大字体": "Increase font size",
        "新对话": "New chat",
        "新建对话": "New conversation",
        "无法启动进程：{0}": "Cannot start the process: {0}",
        "无法打开 GitHub 登录页面": "Cannot open the GitHub sign-in page",
        "无法打开 Google 登录页面": "Cannot open the Google sign-in page",
        "无法执行 {0}：{1}": "Cannot run {0}: {1}",
        "无法连接本地后端：{0}": "Cannot reach the local backend: {0}",
        "显示": "View",
        "暂无日志": "No log entries yet",
        "未检测到 Azure 凭据": "No Azure credentials detected",
        "未检测到 Meraki 凭据": "No Meraki credentials detected",
        "未检测到 Nexus Dashboard 凭据": "No Nexus Dashboard credentials detected",
        "未知错误": "Unknown error",
        "未知（后端未运行）": "Unknown (backend not running)",
        "未运行": "Not running",
        "未配置": "Not configured",
        "未配置 API Key（当前是 mock 模式）": "No API key configured (currently mock mode)",
        "未配置（可选，不影响其它工具）": "Not configured (optional, does not affect the other tools)",
        "本地 AI 对话": "Local AI Chat",
        "本地 Python 后端": "Local Python backend",
        "本地后端正在启动，连上后会自动刷新…": "The local backend is starting; this refreshes automatically once it is up…",
        "本地后端：{0}": "Local backend: {0}",
        "本地管理员（应急入口）": "Local administrator (emergency access)",
        "本轮未触发工具调用": "No tool calls were triggered in this turn",
        "查看结果": "View result",
        "校验 TLS 证书（自签证书请保持关闭）": "Verify the TLS certificate (keep this off for self-signed certificates)",
        "检查中…": "Checking…",
        "检查依赖": "Check dependencies",
        "检测中…": "Probing…",
        "正在提交任务…": "Submitting the task…",
        "每个字段的取值路径：把鼠标停在字段右边的 ? 上。": "Where each value comes from: hover the ? next to the field.",
        "测试中…": "Testing…",
        "测试余额（{0}）": "Check balance ({0})",
        "测试前会先保存当前页面输入，并在需要时重启本地后端，保证测的是这份凭据而不是上次的。": "The current form values are saved first, and the local backend is restarted if needed, so the test really uses these credentials.",
        "测试连接": "Test connection",
        "测试连接会做什么": "What does the connection test do?",
        "清空日志": "Clear logs",
        "点击切换 AI Provider": "Click to switch the AI Provider",
        "用户名": "User name",
        "界面语言": "Interface language",
        "留空则改用下面的用户名密码登录": "Leave empty to sign in with the user name and password below",
        "登录": "Sign in",
        "登录已失效，请重新登录": "Your session has expired, please sign in again",
        "登录状态已失效，请重新登录": "Your session has expired, please sign in again",
        "直接调用 Azure 工具列出订阅：不走 AI、不消耗 token，默认 15 秒超时。": "Calls the Azure tools directly to list subscriptions: no AI, no tokens, 15-second timeout by default.",
        "真实调用：": "Live calls: ",
        "租户 ID": "Tenant ID",
        "第 {0} 次轮询…（已等待 {1}s）": "Poll #{0}… ({1}s elapsed)",
        "第 {0} 轮 · {1} ms": "Round {0} · {1} ms",
        "等待 GitHub 登录…": "Waiting for GitHub sign-in…",
        "等待 Google 登录…": "Waiting for Google sign-in…",
        "等待后端": "Waiting for the backend",
        "继续发送": "Send anyway",
        "缩小字体": "Decrease font size",
        "自动探测": "Detect automatically",
        "解析响应失败：{0}": "Failed to parse the response: {0}",
        "记住密码（保存在 Keychain）": "Remember the password (stored in the Keychain)",
        "设置": "Settings",
        "设置已保存（密钥在 Keychain 中）": "Settings saved (the keys are in the Keychain)",
        "该目标暂不支持测试": "This target does not support testing yet",
        "语言": "Language",
        "请求失败（HTTP {0}）：{1}": "Request failed (HTTP {0}): {1}",
        "调用了 {0} 个工具": "{0} tool calls",
        "走本地后端 {0}/api": "Using the local backend at {0}/api",
        "跟随系统": "System",
        "轮询超时：超过 {0} 次（约 10 分钟）仍未拿到结果": "Polling timed out: no result after {0} attempts (about 10 minutes)",
        "输入内容后发送，应用会调用本地后端的 /api/chat_async，并每 2 秒轮询 /api/ai_task_status 获取结果。": "Type a message and send it; the app calls /api/chat_async on the local backend and polls /api/ai_task_status every 2 seconds for the result.",
        "输入消息，⌘↩ 发送": "Type a message, ⌘↩ to send",
        "运行中": "Running",
        "运行中（外部启动）": "Running (started externally)",
        "进程启动后立即退出，请看下方日志": "The process exited right after starting — see the logs below",
        "进程已退出，请查看下方日志": "The process has exited — see the logs below",
        "连接失败": "Connection failed",
        "连接成功": "Connected successfully",
        "退出": "Quit",
        "退出登录": "Sign out",
        "选择…": "Choose…",
        "选择包含 main.py 的目录": "Choose the directory containing main.py",
        "重启": "Restart",
        "需要在 GitHub OAuth App 设置中启用 Device Flow。用户名和邮箱用逗号分隔；两者都留空会允许所有 GitHub 账号。": "Device Flow must be enabled in the GitHub OAuth app settings. Separate user names and emails with commas; leaving both empty allows any GitHub account.",
        "项目目录": "Project directory",
        "首次使用？点这里检查配置": "First time? Check your setup here",
        "高级选项（开发模式）": "Advanced options (development mode)",
        "默认 Provider": "Default provider",
        "默认 admin / password123，可在后端 .env 里用 ADMIN_USERNAME、ADMIN_PASSWORD 覆盖。": "Default admin / password123; override with ADMIN_USERNAME and ADMIN_PASSWORD in the backend .env.",
        "默认订阅 ID（可留空）": "Default subscription ID (optional)",
        "（Azure 支持环境变量或 az login 凭据；enable_tools=true 时才会调用）": "(Azure accepts environment variables or az login credentials; only used when enable_tools=true)",
        "（后端已完成任务，但返回内容为空）": "(the backend finished the task but returned no content)",
        "（后端是外部启动的，建议在终端里重启）": "(the backend was started externally; restart it in your terminal)",
        "（已回退内存：{0}）": "(fell back to memory: {0})",
        "（无参数）": "(no arguments)",
        "（空结果）": "(empty result)",
    ]
}
