import Foundation

/// 挪威语译文表（Norsk bokmål）
/// key = 源码里写的中文原文（`{0}` / `{1}` 是占位符，见 Localizer.t）
enum LocalizationTableNB {
    static let table: [String: String] = [
        "AI Provider（密钥存 Keychain，启动时传给 Python）": "AI Provider (nøklene ligger i Keychain og sendes til Python ved oppstart)",
        "AI 正在执行工具调用，可能需要 1-2 分钟": "AI-en utfører verktøykall; dette kan ta 1–2 minutter",
        "Azure Foundry 填 https://<资源名>.openai.azure.com/openai/v1": "For Azure Foundry: https://<ressursnavn>.openai.azure.com/openai/v1",
        "Azure Portal → Microsoft Entra ID → 概述 → 租户 ID": "Azure Portal → Microsoft Entra ID → Oversikt → Leier-ID",
        "Azure Portal → 应用注册 → 你的应用 → 应用程序(客户端) ID": "Azure Portal → Appregistreringer → appen din → Program-ID (klient)",
        "Azure Portal → 订阅 → 订阅 ID": "Azure Portal → Abonnementer → Abonnements-ID",
        "Azure 上填部署名（例如 gpt-5.6-sol）；OpenAI 上填模型名": "På Azure skriver du distribusjonsnavnet (f.eks. gpt-5.6-sol); på OpenAI skriver du modellnavnet",
        "Azure 凭据": "Azure-legitimasjon",
        "Azure 工具凭据": "Azure-verktøy: legitimasjon",
        "Azure 工具（enable_tools=true 时使用）": "Azure-verktøy (brukes når enable_tools=true)",
        "Azure：{0}": "Azure: {0}",
        "Bundle 里没有内嵌后端，也没在 {0} 里找到 main.py": "Ingen innebygd backend i appen, og ingen main.py i {0}",
        "Client ID 来自 Google Cloud 的桌面应用 OAuth Client。邮箱和域名用逗号分隔；两者都留空会允许所有 Google 账号。": "Klient-ID-en kommer fra en OAuth-klient for skrivebordsapp i Google Cloud. Skill e-postadresser og domener med komma; lar du begge stå tomme, tillates alle Google-kontoer.",
        "GitHub 登录失败": "GitHub-innlogging mislyktes",
        "GitHub 登录已超时，请重试": "GitHub-innloggingen fikk tidsavbrudd, prøv igjen",
        "GitHub 登录成功，但后端没有返回 JWT": "GitHub-innloggingen lyktes, men backenden returnerte ingen JWT",
        "GitHub 验证码 {0} 已复制，请在浏览器中粘贴": "GitHub-koden {0} er kopiert – lim den inn i nettleseren",
        "Google 登录失败": "Google-innlogging mislyktes",
        "Google 登录已超时，请重试": "Google-innloggingen fikk tidsavbrudd, prøv igjen",
        "Google 登录成功，但后端没有返回 JWT": "Google-innloggingen lyktes, men backenden returnerte ingen JWT",
        "Keychain 中的数据无法解析": "Dataene i Keychain kan ikke leses",
        "Keychain 操作失败，状态码 {0}": "Keychain-operasjonen mislyktes, status {0}",
        "Keychain 操作失败：{0}（{1}）": "Keychain-operasjonen mislyktes: {0} ({1})",
        "Meraki 凭据": "Meraki-legitimasjon",
        "Meraki 工具凭据": "Meraki-verktøy: legitimasjon",
        "Meraki 工具（enable_tools=true 时使用）": "Meraki-verktøy (brukes når enable_tools=true)",
        "Meraki：{0}": "Meraki: {0}",
        "Moonshot / Kimi 开放平台 → API Keys": "Moonshot / Kimi-plattformen → API Keys",
        "Nexus Dashboard 凭据": "Nexus Dashboard-legitimasjon",
        "Nexus Dashboard 工具凭据": "Nexus Dashboard-verktøy: legitimasjon",
        "Nexus Dashboard 工具（官方 Infra API + Manage API）": "Nexus Dashboard-verktøy (offisiell Infra API + Manage API)",
        "Nexus Dashboard 的本地账号（API Key 只对 local 账号有效）": "En lokal Nexus Dashboard-konto (API-nøkler virker bare for lokale kontoer)",
        "Nexus Dashboard 集群地址：只填主机名/IP，不要带 /api/v1/...（后端自动拼 Infra 与 Manage 两套基地址）": "Nexus Dashboard-adresse: bare vertsnavn eller IP, uten /api/v1/... (backenden setter selv sammen både Infra- og Manage-basis-URL-en)",
        "OpenAI: platform.openai.com → API keys；Azure Foundry 用 Azure 门户里的 Key": "OpenAI: platform.openai.com → API keys; for Azure Foundry bruker du nøkkelen fra Azure-portalen",
        "Python 环境": "Python-miljø",
        "Python 解释器": "Python-tolk",
        "Python 解释器不可执行：{0}": "Python-tolken kan ikke kjøres: {0}",
        "memory：重启会丢历史": "memory: historikken forsvinner ved omstart",
        "mock 模式（后端未配置 API Key）": "mock-modus (ingen API-nøkkel konfigurert i backenden)",
        "sk-…（留空则 DeepSeek 走 mock 回复）": "sk-… (tomt felt gir mock-svar fra DeepSeek)",
        "sk-…（留空则 Kimi 走 mock 回复）": "sk-… (tomt felt gir mock-svar fra Kimi)",
        "sk-…（留空则 OpenAI 走 mock 回复）": "sk-… (tomt felt gir mock-svar fra OpenAI)",
        "sqlite（重启保留历史）": "sqlite (historikken beholdes ved omstart)",
        "{0} 条消息": "{0} meldinger",
        "{0}：重启可能丢历史": "{0}: historikken kan forsvinne ved omstart",
        "{0}｜原始响应：{1}": "{0}｜Råsvar: {1}",
        "⚠ 有失败": "⚠ feil",
        "✓ 可以登录了（存储为 memory，重启会丢历史）": "✓ Du kan logge inn (lagringen er memory, historikken forsvinner ved omstart)",
        "✓ 配置完整，可以登录了": "✓ Alt er konfigurert, du kan logge inn",
        "一键重启并测试": "Start på nytt og test",
        "仅在不用 API Key 时填写": "Fylles bare ut hvis du ikke bruker API-nøkkel",
        "任务已受理（{0}…），等待结果…": "Oppgaven er mottatt ({0}…), venter på resultatet…",
        "任务执行失败": "Oppgaven mislyktes",
        "会话": "Samtaler",
        "使用 GitHub 账号登录": "Logg inn med GitHub",
        "使用 Google 账号登录": "Logg inn med Google",
        "依赖检查通过（原生 arm64）：{0}": "Avhengighetssjekk OK (native arm64): {0}",
        "保存 Azure 凭据": "Lagre Azure-legitimasjon",
        "保存 Meraki 凭据": "Lagre Meraki-legitimasjon",
        "保存 Nexus Dashboard 凭据": "Lagre Nexus Dashboard-legitimasjon",
        "保存凭据失败：{0}": "Kunne ikke lagre legitimasjonen: {0}",
        "保存到 Keychain": "Lagre i Keychain",
        "保存失败：{0}": "Lagring mislyktes: {0}",
        "保存并重启后端": "Lagre og start backenden på nytt",
        "保存设置": "Lagre innstillinger",
        "停止": "Stopp",
        "允许的域名": "Tillatte domener",
        "允许的用户名": "Tillatte brukernavn",
        "允许的邮箱": "Tillatte e-postadresser",
        "关闭": "Lukk",
        "内嵌后端已就绪": "Innebygd backend er klar",
        "写入 .env": "Skriv .env",
        "写入失败：{0}": "Skriving mislyktes: {0}",
        "凭据已更新，需要重启后端生效": "Legitimasjonen er oppdatert, start backenden på nytt for at den skal gjelde",
        "切换语言后立即生效，不用重启应用。": "Trer i kraft med en gang – du trenger ikke starte appen på nytt.",
        "删除这个会话": "Slett denne samtalen",
        "刷新状态": "Oppdater status",
        "去配置": "Konfigurer",
        "发送": "Send",
        "取消": "Avbryt",
        "只有在没有内嵌后端、需要跑项目里的 main.py 时才会用到这两项。": "Disse to trengs bare når det ikke finnes noen innebygd backend og main.py i prosjektmappen må brukes.",
        "只读工具：Infra API 覆盖集群/节点/健康/容量/许可/租户/集成，Manage API 覆盖 fabric/交换机/接口/网络/VRF，不含任何写操作。": "Skrivebeskyttede verktøy: Infra API dekker klynger/noder/helse/kapasitet/lisenser/leiere/integrasjoner, Manage API dekker fabric/svitsjer/grensesnitt/nettverk/VRF-er. Ingen skriveoperasjoner.",
        "右上角用户名 → Manage API keys → Add API key。留空则后端用 ND_PASSWORD 调 /api/v1/infra/login 换 token": "Brukernavn øverst til høyre → Manage API keys → Add API key. Står feltet tomt, bruker backenden ND_PASSWORD mot /api/v1/infra/login for å hente token",
        "后端 {0} 秒内没有响应，请检查依赖与日志": "Backenden svarte ikke innen {0} sekunder; sjekk avhengigheter og loggen",
        "后端地址": "Backend-adresse",
        "后端地址无效：{0}": "Ugyldig backend-adresse: {0}",
        "后端日志": "Backend-logg",
        "后端未上报存储类型": "Backenden rapporterte ikke lagringstype",
        "后端未启用工具，请检查设置": "Verktøy er ikke aktivert i backenden – sjekk innstillingene",
        "后端未运行": "Backenden kjører ikke",
        "后端未运行，需要先启动后端": "Backenden kjører ikke, start den først",
        "后端模式：内嵌 backend_server（下次启动生效）｜日志：{0}": "Backend-modus: innebygd backend_server (gjelder ved neste oppstart)｜Logg: {0}",
        "后端模式：内嵌 backend_server｜日志：{0}": "Backend-modus: innebygd backend_server｜Logg: {0}",
        "后端模式：开发模式（没找到内嵌 backend_server，回退到项目目录 + Python）": "Backend-modus: utviklingsmodus (fant ingen innebygd backend_server, faller tilbake til prosjektmappen + Python)",
        "后端没起来：{0}": "Backenden startet ikke: {0}",
        "后端状态异常：{0}": "Uventet backend-status: {0}",
        "后端进程": "Backend-prosess",
        "后端重启失败：{0}": "Kunne ikke starte backenden på nytt: {0}",
        "启动": "Start",
        "启动中…": "Starter…",
        "启动后端": "Start backenden",
        "启动失败：{0}": "Oppstart mislyktes: {0}",
        "启动应用时自动拉起本地后端": "Start den lokale backenden automatisk når appen åpnes",
        "启动时把设置写入项目根目录的 .env": "Skriv innstillingene til .env i prosjektroten ved oppstart",
        "响应为空": "Tomt svar",
        "响应类型异常": "Uventet svartype",
        "字体大小 {0}%": "Skriftstørrelse {0} %",
        "存储": "Lagring",
        "存储后端：": "Lagringsmotor:",
        "客户端密码的 Value": "Verdien av klienthemmeligheten",
        "密码": "Passord",
        "密码模式的登录域，本地账号填 local；对接外部认证域时填对应域名": "Innloggingsdomene for passordmodus; bruk local for lokale kontoer, eller det aktuelle domenet for ekstern autentisering",
        "密码模式：后端 POST /api/v1/infra/login 拿 jwttoken，进程内缓存 10 分钟后自动续期": "Passordmodus: backenden POST-er til /api/v1/infra/login for å hente JWT, bufrer den i 10 minutter og fornyer automatisk",
        "对话": "Chat",
        "工具": "Verktøy",
        "工具凭据：": "Verktøy-legitimasjon:",
        "工具调用已关闭，纯对话模式": "Verktøykall er av – vanlig chat",
        "工具调用已开启，AI 可执行 Azure/Meraki 查询": "Verktøykall er på – AI-en kan gjøre Azure/Meraki-spørringer",
        "已使用 GitHub 账号登录": "Logget inn med GitHub",
        "已使用 Google 账号登录": "Logget inn med Google",
        "已写入：{0}": "Skrevet til: {0}",
        "已取消本次请求": "Forespørselen ble avbrutt",
        "已启用工具调用": "Verktøykall er aktivert",
        "已启用工具调用：AI 可能会查询你的 Azure 订阅或 Meraki 网络。每次调用都会在气泡中显示。": "Verktøykall er aktivert: AI-en kan spørre i Azure-abonnementene eller Meraki-nettene dine. Hvert kall vises i meldingsboblen.",
        "已就绪（后端未上报版本）": "Klar (backenden rapporterte ingen versjon)",
        "已检测到 Azure 凭据": "Azure-legitimasjon funnet",
        "已检测到 Meraki 凭据": "Meraki-legitimasjon funnet",
        "已检测到 Nexus Dashboard 凭据": "Nexus Dashboard-legitimasjon funnet",
        "已连接 {0}": "Tilkoblet {0}",
        "已退出登录": "Logget ut",
        "已配置": "Konfigurert",
        "已配置 {0}": "Konfigurert: {0}",
        "已配置（az login 凭据）": "Konfigurert (az login-legitimasjon)",
        "已配置（环境变量）": "Konfigurert (miljøvariabler)",
        "应用注册 → 证书和密码 → 新客户端密码（复制 Value，不是 Secret ID）": "Appregistreringer → Sertifikater og hemmeligheter → Ny klienthemmelighet (kopier verdien, ikke hemmelighets-ID-en)",
        "应用（客户端）ID": "Program-ID (klient)",
        "开始新的对话": "Start en ny samtale",
        "当前后端进程：{0}。凭据改动需要重启后端才会生效。": "Gjeldende backend-prosess: {0}. Endringer i legitimasjonen gjelder etter at backenden er startet på nytt.",
        "恢复默认字体大小": "Tilbakestill skriftstørrelsen",
        "我": "Meg",
        "或使用本地管理员（应急入口）": "Eller bruk den lokale administratoren (nødtilgang)",
        "打开后端日志": "Åpne backend-loggen",
        "放大字体": "Større skrift",
        "新对话": "Ny chat",
        "新建对话": "Ny samtale",
        "无法启动进程：{0}": "Kan ikke starte prosessen: {0}",
        "无法打开 GitHub 登录页面": "Kan ikke åpne GitHub-innloggingssiden",
        "无法打开 Google 登录页面": "Kan ikke åpne Google-innloggingssiden",
        "无法执行 {0}：{1}": "Kan ikke kjøre {0}: {1}",
        "无法连接本地后端：{0}": "Får ikke kontakt med den lokale backenden: {0}",
        "显示": "Vis",
        "暂无日志": "Ingen logglinjer ennå",
        "未检测到 Azure 凭据": "Fant ingen Azure-legitimasjon",
        "未检测到 Meraki 凭据": "Fant ingen Meraki-legitimasjon",
        "未检测到 Nexus Dashboard 凭据": "Fant ingen Nexus Dashboard-legitimasjon",
        "未知错误": "Ukjent feil",
        "未知（后端未运行）": "Ukjent (backenden kjører ikke)",
        "未运行": "Kjører ikke",
        "未配置": "Ikke konfigurert",
        "未配置 API Key（当前是 mock 模式）": "Ingen API-nøkkel konfigurert (mock-modus nå)",
        "未配置（可选，不影响其它工具）": "Ikke konfigurert (valgfritt, påvirker ikke de andre verktøyene)",
        "本地 AI 对话": "Lokal AI-chat",
        "本地 Python 后端": "Lokal Python-backend",
        "本地后端正在启动，连上后会自动刷新…": "Den lokale backenden starter; dette oppdateres automatisk når den er oppe…",
        "本地后端：{0}": "Lokal backend: {0}",
        "本地管理员（应急入口）": "Lokal administrator (nødtilgang)",
        "本轮未触发工具调用": "Ingen verktøykall ble utløst i denne runden",
        "查看结果": "Vis resultat",
        "校验 TLS 证书（自签证书请保持关闭）": "Bekreft TLS-sertifikatet (la dette stå av for selvsignerte sertifikater)",
        "检查中…": "Sjekker…",
        "检查依赖": "Sjekk avhengigheter",
        "检测中…": "Søker…",
        "正在提交任务…": "Sender oppgaven…",
        "每个字段的取值路径：把鼠标停在字段右边的 ? 上。": "Hvor hver verdi hentes fra: hold markøren over ? ved siden av feltet.",
        "测试中…": "Tester…",
        "测试余额（{0}）": "Sjekk saldo ({0})",
        "测试前会先保存当前页面输入，并在需要时重启本地后端，保证测的是这份凭据而不是上次的。": "Verdiene i skjemaet lagres først, og den lokale backenden startes på nytt om nødvendig, slik at testen virkelig bruker denne legitimasjonen.",
        "测试连接": "Test tilkobling",
        "测试连接会做什么": "Hva gjør tilkoblingstesten?",
        "清空日志": "Tøm loggen",
        "点击切换 AI Provider": "Klikk for å bytte AI Provider",
        "用户名": "Brukernavn",
        "界面语言": "Grensesnittspråk",
        "留空则改用下面的用户名密码登录": "La stå tomt for å logge inn med brukernavnet og passordet nedenfor",
        "登录": "Logg inn",
        "登录已失效，请重新登录": "Økten er utløpt, logg inn på nytt",
        "登录状态已失效，请重新登录": "Økten er utløpt, logg inn på nytt",
        "直接调用 Azure 工具列出订阅：不走 AI、不消耗 token，默认 15 秒超时。": "Kaller Azure-verktøyene direkte for å liste abonnementer: ingen AI, ingen tokens, 15 sekunders tidsavbrudd.",
        "真实调用：": "Ekte kall: ",
        "租户 ID": "Leier-ID",
        "第 {0} 次轮询…（已等待 {1}s）": "Forsøk {0}… ({1}s ventetid)",
        "第 {0} 轮 · {1} ms": "Runde {0} · {1} ms",
        "等待 GitHub 登录…": "Venter på GitHub-innlogging…",
        "等待 Google 登录…": "Venter på Google-innlogging…",
        "等待后端": "Venter på backenden",
        "继续发送": "Send likevel",
        "缩小字体": "Mindre skrift",
        "自动探测": "Finn automatisk",
        "解析响应失败：{0}": "Kunne ikke lese svaret: {0}",
        "记住密码（保存在 Keychain）": "Husk passordet (lagres i Keychain)",
        "设置": "Innstillinger",
        "设置已保存（密钥在 Keychain 中）": "Innstillingene er lagret (nøklene ligger i Keychain)",
        "该目标暂不支持测试": "Dette målet støtter ikke test ennå",
        "语言": "Språk",
        "请求失败（HTTP {0}）：{1}": "Forespørselen mislyktes (HTTP {0}): {1}",
        "调用了 {0} 个工具": "{0} verktøykall",
        "走本地后端 {0}/api": "Bruker lokal backend {0}/api",
        "跟随系统": "Følg systemet",
        "轮询超时：超过 {0} 次（约 10 分钟）仍未拿到结果": "Tidsavbrudd: ingen resultat etter {0} forsøk (omtrent 10 minutter)",
        "输入内容后发送，应用会调用本地后端的 /api/chat_async，并每 2 秒轮询 /api/ai_task_status 获取结果。": "Skriv en melding og send den; appen kaller /api/chat_async på den lokale backenden og spør /api/ai_task_status hvert 2. sekund om resultatet.",
        "输入消息，⌘↩ 发送": "Skriv en melding, ⌘↩ for å sende",
        "运行中": "Kjører",
        "运行中（外部启动）": "Kjører (startet eksternt)",
        "进程启动后立即退出，请看下方日志": "Prosessen avsluttet rett etter oppstart – se loggen nedenfor",
        "进程已退出，请查看下方日志": "Prosessen har avsluttet – se loggen nedenfor",
        "连接失败": "Tilkoblingen mislyktes",
        "连接成功": "Tilkoblingen lyktes",
        "退出": "Avslutt",
        "退出登录": "Logg ut",
        "选择…": "Velg…",
        "选择包含 main.py 的目录": "Velg mappen som inneholder main.py",
        "重启": "Start på nytt",
        "需要在 GitHub OAuth App 设置中启用 Device Flow。用户名和邮箱用逗号分隔；两者都留空会允许所有 GitHub 账号。": "Device Flow må være aktivert i innstillingene for GitHub OAuth-appen. Skill brukernavn og e-postadresser med komma; lar du begge stå tomme, tillates alle GitHub-kontoer.",
        "项目目录": "Prosjektmappe",
        "首次使用？点这里检查配置": "Første gang? Sjekk oppsettet her",
        "高级选项（开发模式）": "Avanserte valg (utviklingsmodus)",
        "默认 Provider": "Standard Provider",
        "默认 admin / password123，可在后端 .env 里用 ADMIN_USERNAME、ADMIN_PASSWORD 覆盖。": "Standard admin / password123; kan overstyres med ADMIN_USERNAME og ADMIN_PASSWORD i backendens .env.",
        "默认订阅 ID（可留空）": "Standard abonnements-ID (valgfritt)",
        "（Azure 支持环境变量或 az login 凭据；enable_tools=true 时才会调用）": "(Azure godtar miljøvariabler eller az login-legitimasjon; brukes bare når enable_tools=true)",
        "（后端已完成任务，但返回内容为空）": "(backenden fullførte oppgaven, men returnerte ikke noe innhold)",
        "（后端是外部启动的，建议在终端里重启）": "(backenden ble startet eksternt; start den på nytt i terminalen)",
        "（已回退内存：{0}）": "(falt tilbake til memory: {0})",
        "（无参数）": "(ingen argumenter)",
        "（空结果）": "(tomt resultat)",
    ]
}
